#pragma once

#include <stdbool.h>
#include "esp_err.h"

#ifdef __cplusplus
extern "C" {
#endif

/*
 * TFLite Micro inference.
 *
 * PLAIN-LANGUAGE SUMMARY:
 * This takes the 13 numbers from feature_extraction and runs them
 * through the trained stress-detection model, producing a class
 * (0 = baseline, 1 = watch, 2 = confirmed stress) and the raw
 * probability behind that decision.
 *
 * IMPORTANT — THIS CANNOT WORK YET WITHOUT ONE FILE FROM YOU:
 * The actual trained model (stress_nn_data.h) is generated by your
 * Kaggle notebook, from real training data — it is not something that
 * can be written here. A clearly-marked placeholder sits at
 * components/tflite_inference/model/stress_nn_data.h right now. Delete
 * its contents and paste in the real xxd-generated array from your
 * Kaggle output (see ml_pipeline_documentation.md, Section 12) before
 * this will do anything meaningful. Until then, this component is
 * structurally complete but will refuse to build (the placeholder
 * contains a deliberate #error) rather than silently pretend to work.
 *
 * ALSO CARRIED FORWARD, PER chat2_firmware_handoff.md's OWN OPEN
 * QUESTIONS: the tensor arena size below is a reasonable starting
 * guess, not an empirically-confirmed value — that document explicitly
 * flags arena sizing as something that must be determined on real
 * hardware. Watch the init log for an allocation failure once the real
 * model is in place; if it fails, the arena needs to grow.
 */

esp_err_t tflite_inference_init(void);

// TEMPORARY, until the BLE calibration protocol (ble_gatt_contract_handoff.md)
// is built: sets the per-feature mean/std used to normalise inputs
// before they reach the model. Until this is called, inputs pass
// through UN-normalised (mean=0, std=1 for all 13), which is almost
// certainly wrong for real inference — the model was trained on
// z-scored features. This exists so the harness is complete and ready
// to be wired to real calibration data the moment that component
// exists.
void tflite_inference_set_calibration(const float mean[13], const float std[13]);

// Runs one inference. features must be exactly 13 values, in the order
// locked in feature_extraction.h / chat2_firmware_handoff.md.
// Returns true and fills the outputs on success.
bool tflite_inference_run(const float features[13], int *out_class, float *out_probability);

#ifdef __cplusplus
}
#endif
